export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';
export const ADD_TO_SUBLIST = 'ADD_TO_SUBLIST';
export const TOGGLE_ADDING_FORM = 'TOGGLE_ADDING_FORM';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const NEW_GROUP_CAT = 'NEW_GROUP_CAT';
export const UPDATE_SUBCAT_NAME = 'UPDATE_SUBCAT_NAME';
export const UPDATE_SUBCAT_NAME_TRANS = 'UPDATE_SUBCATE_NAME_TRANS';
export const NEW_SUBCAT = 'NEW_SUBCAT';